site_name: FL Studio API Documentation
site_description: Documentation for the FL Studio API
repo_name: FL-Studio-API-Stubs
repo_url: https://github.com/IL-Group/FL-Studio-API-Stubs
copyright: (C) 2024 Image Line Software

# Build to a temporary directory
site_dir: temp_site

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  logo: assets/logo-monochrome.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tracking

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths:
            - prebuild_docs
          options:
            show_source: false
  ## Not using mkdocs scripts since we need to do a ton of pre-build stuff
  ## Maybe I'll try and get this working some point
  # - gen-files:
  #     scripts:
  #       - scripts/generate_pages.py

markdown_extensions:
  - toc:
      title: Contents
      toc_depth: 2

extra_css:
  - stylesheets/extra.css

docs_dir: build_docs
