site_name: FL Studio Python API
site_description: Documentation for the FL Studio Python API
repo_name: "IL-Group/FL-Studio-API-Stubs"
repo_url: https://github.com/IL-Group/FL-Studio-API-Stubs
copyright: © 2024 Image Line Software

# Build to a temporary directory
site_dir: temp_site

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  logo: assets/logo-monochrome.png
  favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github
    code: fontawesome/solid/code
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - content.code.copy

plugins:
  - awesome-pages:
      collapse_single_pages: true
  - section-index
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths:
            - prebuild_docs/midi_controller_scripting
            - prebuild_docs/edison_scripting
            - prebuild_docs/piano_roll_scripting
          options:
            show_source: false
            show_signature_annotations: true
            separate_signature: true
            members_order: source
  - search

  ## Not using mkdocs scripts since we need to do a ton of pre-build stuff
  ## Maybe I'll try and get this working some point
  # - gen-files:
  #     scripts:
  #       - scripts/generate_pages.py

markdown_extensions:
  - toc:
      title: Contents
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/removeDunderToc.js

docs_dir: build_docs
