[tool.poetry]
name = "fl-studio-api-stubs"
version = "28.0.0"
description = "Stub definitions for FL Studio's Python API"
authors = ["Miguel Guthridge <hdsq@outlook.com.au>"]
license = "LGPLv3"

[tool.poetry.dependencies]
python = "^3.9.1"
jsonschema = "^4.17.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"
mypy = "^1.1.1"
flake8 = "^6.0.0"
typing-extensions = "^4.5.0"
coverage = "^7.2.2"
types-jsonschema = "^4.17.0"
mkdocs = "^1.4.2"
mkdocs-gen-files = "^0.4.0"
mkdocs-autorefs = "^0.4.1"
mkdocs-material = "^8.5.11"
mkdocs-material-extensions = "^1.1.1"
mkdocstrings = "^0.20.0"
mkdocstrings-python = "^0.8.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
