[tool.poetry]
name = "fl-studio-api-stubs"
version = "28.0.0"
description = "Stub definitions for FL Studio's Python API"
authors = ["Miguel Guthridge <hdsq@outlook.com.au>"]
license = "LGPLv3"

[tool.poetry.dependencies]
python = "^3.9.1"
jsonschema = "^4.17.3"
mkdocs = "^1.4.2"
mkdocs-material = "^9.1.3"

[tool.poetry.dev-dependencies]
pytest = "^7.2.2"
mypy = "^1.1.1"
flake8 = "^6.0.0"
typing-extensions = "^4.5.0"
coverage = "^7.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
