name: Generate Documentation and deploy to GitHub pages
on:
  # Documentation can be either manually updated or is automatically updated when pushed to main branch
  workflow_dispatch:
  push:
    branches:
      - main

# Make sure deploy-pages has necessary permissions to 
permissions:
  pages: write
  id-token: write

# Cancel older deploy workflow when more than one is running
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy 
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }} # Output URL after the workflow has finished
    steps:
      # Checkout repository including submodules
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      # Setup Python 3.10
      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      # Install pip dependencies from requirements.txt
      - name: Install Dependencies
        id: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Build documentation to ./site/ directory
      - name: Build Documentation
        id: build
        run: mkdocs build
    
      # Upload artifact from the ./site/ directory the expected format for GitHub Pages
      - name: Upload Artifact
        id: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site/
      
      # Use previously uploaded artifact to deploy to GitHub Pages
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v1
