name: Generate Documentation and deploy to GitHub pages
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    name: Build and Deploy 
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        id: dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Documentation
        id: build
        run: mkdocs build

      - name: Upload Artifact
        id: upload
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./site/
          
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v1
